[2023-12-21T00:00:23.873+0000] {processor.py:161} INFO - Started process (PID=58781) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:00:23.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:00:23.877+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:00:23.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:00:23.881+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:00:23.880+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:00:23.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:00:23.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.049 seconds
[2023-12-21T00:00:54.399+0000] {processor.py:161} INFO - Started process (PID=58837) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:00:54.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:00:54.404+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:00:54.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:00:54.408+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:00:54.407+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:00:54.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:00:54.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.054 seconds
[2023-12-21T00:01:24.968+0000] {processor.py:161} INFO - Started process (PID=58894) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:01:24.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:01:24.972+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:01:24.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:01:24.977+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:01:24.976+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:01:24.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:01:25.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.333 seconds
[2023-12-21T00:01:56.059+0000] {processor.py:161} INFO - Started process (PID=58949) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:01:56.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:01:56.063+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:01:56.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:01:56.070+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:01:56.067+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:01:56.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:01:56.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.329 seconds
[2023-12-21T00:02:27.181+0000] {processor.py:161} INFO - Started process (PID=59004) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:02:27.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:02:27.298+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:02:27.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:02:27.305+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:02:27.304+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:02:27.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:02:27.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.212 seconds
[2023-12-21T00:02:58.205+0000] {processor.py:161} INFO - Started process (PID=59059) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:02:58.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:02:58.209+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:02:58.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:02:58.215+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:02:58.213+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:02:58.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:02:58.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.077 seconds
[2023-12-21T00:03:28.524+0000] {processor.py:161} INFO - Started process (PID=59115) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:03:28.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:03:28.539+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:03:28.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:03:28.543+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:03:28.542+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:03:28.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:03:28.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.071 seconds
[2023-12-21T00:03:58.751+0000] {processor.py:161} INFO - Started process (PID=59171) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:03:58.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:03:58.758+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:03:58.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:03:58.761+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:03:58.761+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:03:58.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:03:58.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.254 seconds
[2023-12-21T00:04:29.430+0000] {processor.py:161} INFO - Started process (PID=59227) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:04:29.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:04:29.437+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:04:29.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:04:29.440+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:04:29.439+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:04:29.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:04:29.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.060 seconds
[2023-12-21T00:04:59.794+0000] {processor.py:161} INFO - Started process (PID=59283) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:04:59.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:04:59.800+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:04:59.799+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:04:59.805+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:04:59.804+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:04:59.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:04:59.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.060 seconds
[2023-12-21T00:05:30.205+0000] {processor.py:161} INFO - Started process (PID=59339) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:05:30.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:05:30.209+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:05:30.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:05:30.212+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:05:30.211+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:05:30.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:05:30.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.058 seconds
[2023-12-21T00:06:00.669+0000] {processor.py:161} INFO - Started process (PID=59395) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:06:00.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:06:00.673+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:06:00.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:06:00.677+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:06:00.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:06:00.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:06:00.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.058 seconds
[2023-12-21T00:06:31.265+0000] {processor.py:161} INFO - Started process (PID=59451) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:06:31.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:06:31.274+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:06:31.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:06:31.280+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:06:31.278+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:06:31.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:06:31.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.072 seconds
[2023-12-21T00:07:01.920+0000] {processor.py:161} INFO - Started process (PID=59507) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:07:01.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:07:01.924+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:07:01.923+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:07:01.928+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:07:01.927+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:07:01.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:07:01.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.044 seconds
[2023-12-21T00:07:32.696+0000] {processor.py:161} INFO - Started process (PID=59563) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:07:32.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:07:32.701+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:07:32.701+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:07:32.706+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:07:32.705+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:07:32.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:07:32.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.052 seconds
[2023-12-21T00:08:02.979+0000] {processor.py:161} INFO - Started process (PID=59619) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:08:02.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:08:02.988+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:08:02.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:08:02.991+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:08:02.991+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:08:02.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:08:03.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.057 seconds
[2023-12-21T00:08:33.065+0000] {processor.py:161} INFO - Started process (PID=59675) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:08:33.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:08:33.069+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:08:33.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:08:33.073+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:08:33.072+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:08:33.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:08:33.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.058 seconds
[2023-12-21T00:09:03.425+0000] {processor.py:161} INFO - Started process (PID=59729) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:09:03.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:09:03.429+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:09:03.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:09:03.434+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:09:03.432+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:09:03.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:09:03.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.052 seconds
[2023-12-21T00:09:33.930+0000] {processor.py:161} INFO - Started process (PID=59784) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:09:33.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:09:33.934+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:09:33.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:09:33.940+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:09:33.939+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:09:33.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:09:34.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.164 seconds
[2023-12-21T00:10:04.339+0000] {processor.py:161} INFO - Started process (PID=59834) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:10:04.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:10:04.344+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:10:04.343+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:10:04.348+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:10:04.347+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:10:04.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:10:04.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.099 seconds
[2023-12-21T00:10:35.126+0000] {processor.py:161} INFO - Started process (PID=59890) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:10:35.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:10:35.155+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:10:35.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:10:35.185+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:10:35.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:10:35.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:10:35.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.196 seconds
[2023-12-21T00:11:06.316+0000] {processor.py:161} INFO - Started process (PID=59946) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:11:06.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:11:06.321+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:11:06.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:11:06.328+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:11:06.326+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:11:06.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:11:06.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.080 seconds
[2023-12-21T00:11:36.662+0000] {processor.py:161} INFO - Started process (PID=60002) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:11:36.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:11:36.690+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:11:36.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:11:36.696+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:11:36.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:11:36.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:11:36.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.122 seconds
[2023-12-21T00:12:07.088+0000] {processor.py:161} INFO - Started process (PID=60058) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:12:07.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:12:07.094+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:12:07.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:12:07.100+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:12:07.099+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:12:07.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:12:07.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.116 seconds
[2023-12-21T00:12:38.032+0000] {processor.py:161} INFO - Started process (PID=60114) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:12:38.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:12:38.039+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:12:38.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:12:38.045+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:12:38.044+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:12:38.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:12:38.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.068 seconds
[2023-12-21T00:13:08.768+0000] {processor.py:161} INFO - Started process (PID=60170) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:13:08.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:13:08.774+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:13:08.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:13:08.780+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:13:08.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:13:08.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:13:08.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.060 seconds
[2023-12-21T00:13:39.152+0000] {processor.py:161} INFO - Started process (PID=60226) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:13:39.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:13:39.159+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:13:39.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:13:39.165+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:13:39.164+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:13:39.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:13:39.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.052 seconds
[2023-12-21T00:14:09.959+0000] {processor.py:161} INFO - Started process (PID=60282) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:14:09.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:14:09.965+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:14:09.964+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:14:09.971+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:14:09.969+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:14:09.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:14:10.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.055 seconds
[2023-12-21T00:14:40.842+0000] {processor.py:161} INFO - Started process (PID=60337) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:14:40.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:14:40.853+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:14:40.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:14:40.859+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:14:40.857+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:14:40.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:14:40.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.056 seconds
[2023-12-21T00:15:11.020+0000] {processor.py:161} INFO - Started process (PID=60393) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:15:11.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:15:11.023+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:15:11.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:15:11.031+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:15:11.027+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:15:11.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:15:11.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.063 seconds
[2023-12-21T00:15:41.922+0000] {processor.py:161} INFO - Started process (PID=60449) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:15:41.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:15:41.948+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:15:41.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:15:41.954+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:15:41.952+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:15:41.955+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:15:42.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.091 seconds
[2023-12-21T00:16:12.665+0000] {processor.py:161} INFO - Started process (PID=60504) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:16:12.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:16:12.670+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:16:12.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:16:12.676+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:16:12.674+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:16:12.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:16:12.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.070 seconds
[2023-12-21T00:16:42.898+0000] {processor.py:161} INFO - Started process (PID=60560) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:16:42.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:16:42.902+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:16:42.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:16:42.907+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:16:42.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:16:42.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:16:42.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.057 seconds
[2023-12-21T00:17:13.649+0000] {processor.py:161} INFO - Started process (PID=60617) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:17:13.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:17:13.653+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:17:13.653+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:17:13.660+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:17:13.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:17:13.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:17:13.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.069 seconds
[2023-12-21T00:17:43.959+0000] {processor.py:161} INFO - Started process (PID=60672) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:17:43.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:17:43.963+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:17:43.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:17:43.968+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:17:43.966+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:17:43.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:17:44.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.065 seconds
[2023-12-21T00:18:14.674+0000] {processor.py:161} INFO - Started process (PID=60728) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:18:14.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:18:14.677+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:18:14.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:18:14.683+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:18:14.681+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:18:14.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:18:14.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.058 seconds
[2023-12-21T00:18:45.223+0000] {processor.py:161} INFO - Started process (PID=60783) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:18:45.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:18:45.266+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:18:45.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:18:45.271+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:18:45.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:18:45.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:18:45.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.130 seconds
[2023-12-21T00:19:15.815+0000] {processor.py:161} INFO - Started process (PID=60838) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:19:15.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:19:15.820+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:19:15.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:19:15.829+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:19:15.826+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:19:15.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:19:15.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.069 seconds
[2023-12-21T00:19:46.186+0000] {processor.py:161} INFO - Started process (PID=60893) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:19:46.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:19:46.189+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:19:46.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:19:46.193+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:19:46.192+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:19:46.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:19:46.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.062 seconds
[2023-12-21T00:20:16.575+0000] {processor.py:161} INFO - Started process (PID=60950) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:20:16.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:20:16.579+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:20:16.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:20:16.584+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:20:16.582+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:20:16.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:20:16.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.081 seconds
[2023-12-21T00:20:46.895+0000] {processor.py:161} INFO - Started process (PID=61006) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:20:46.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:20:46.899+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:20:46.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:20:46.905+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:20:46.904+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:20:46.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:20:46.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.081 seconds
[2023-12-21T00:21:17.332+0000] {processor.py:161} INFO - Started process (PID=61061) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:21:17.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:21:17.336+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:21:17.336+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:21:17.342+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:21:17.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:21:17.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:21:17.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.078 seconds
[2023-12-21T00:21:47.959+0000] {processor.py:161} INFO - Started process (PID=61117) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:21:47.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:21:47.984+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:21:47.983+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:21:47.990+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:21:47.988+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:21:47.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:21:48.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.375 seconds
[2023-12-21T00:22:18.526+0000] {processor.py:161} INFO - Started process (PID=61173) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:22:18.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:22:18.529+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:22:18.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:22:18.534+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:22:18.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:22:18.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:22:18.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.068 seconds
[2023-12-21T00:22:49.179+0000] {processor.py:161} INFO - Started process (PID=61229) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:22:49.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:22:49.182+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:22:49.182+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:22:49.188+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:22:49.185+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:22:49.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:22:49.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.121 seconds
[2023-12-21T00:23:19.996+0000] {processor.py:161} INFO - Started process (PID=61285) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:23:19.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:23:20.001+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:23:20.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:23:20.008+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:23:20.006+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:23:20.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:23:20.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.093 seconds
[2023-12-21T00:23:50.609+0000] {processor.py:161} INFO - Started process (PID=61340) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:23:50.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:23:50.633+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:23:50.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:23:50.641+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:23:50.636+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:23:50.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:23:50.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.253 seconds
[2023-12-21T00:24:21.215+0000] {processor.py:161} INFO - Started process (PID=61396) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:24:21.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:24:21.220+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:24:21.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:24:21.228+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:24:21.225+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:24:21.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:24:21.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.077 seconds
[2023-12-21T00:24:52.131+0000] {processor.py:161} INFO - Started process (PID=61452) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:24:52.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:24:52.159+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:24:52.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:24:52.164+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:24:52.162+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:24:52.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:24:52.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.089 seconds
[2023-12-21T00:25:22.381+0000] {processor.py:161} INFO - Started process (PID=61507) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:25:22.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:25:22.387+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:25:22.387+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:25:22.396+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:25:22.392+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:25:22.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:25:22.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.072 seconds
[2023-12-21T00:25:52.622+0000] {processor.py:161} INFO - Started process (PID=61563) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:25:52.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:25:52.646+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:25:52.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:25:52.650+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:25:52.649+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:25:52.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:25:52.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.073 seconds
[2023-12-21T00:26:23.317+0000] {processor.py:161} INFO - Started process (PID=61618) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:26:23.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:26:23.320+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:26:23.320+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:26:23.324+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:26:23.323+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:26:23.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:26:23.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.066 seconds
[2023-12-21T00:26:53.417+0000] {processor.py:161} INFO - Started process (PID=61674) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:26:53.442+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:26:53.445+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:26:53.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:26:53.448+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:26:53.447+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:26:53.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:26:53.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.075 seconds
[2023-12-21T00:27:23.690+0000] {processor.py:161} INFO - Started process (PID=61729) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:27:23.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:27:23.693+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:27:23.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:27:23.697+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:27:23.696+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:27:23.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:27:23.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.056 seconds
[2023-12-21T00:27:54.345+0000] {processor.py:161} INFO - Started process (PID=61785) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:27:54.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:27:54.362+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:27:54.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:27:54.368+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:27:54.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:27:54.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:27:54.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.078 seconds
[2023-12-21T00:28:25.206+0000] {processor.py:161} INFO - Started process (PID=61840) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:28:25.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:28:25.210+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:28:25.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:28:25.215+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:28:25.214+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:28:25.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:28:25.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.055 seconds
[2023-12-21T00:28:55.551+0000] {processor.py:161} INFO - Started process (PID=61896) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:28:55.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:28:55.557+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:28:55.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:28:55.562+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:28:55.561+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:28:55.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:28:55.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.066 seconds
[2023-12-21T00:29:26.201+0000] {processor.py:161} INFO - Started process (PID=61951) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:29:26.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:29:26.206+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:29:26.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:29:26.211+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:29:26.210+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:29:26.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:29:26.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.078 seconds
[2023-12-21T00:29:56.907+0000] {processor.py:161} INFO - Started process (PID=62007) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:29:56.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:29:56.912+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:29:56.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:29:56.918+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:29:56.916+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:29:56.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:29:56.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.069 seconds
[2023-12-21T00:30:27.423+0000] {processor.py:161} INFO - Started process (PID=62062) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:30:27.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:30:27.428+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:30:27.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:30:27.432+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:30:27.431+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:30:27.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:30:27.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.102 seconds
[2023-12-21T00:30:57.851+0000] {processor.py:161} INFO - Started process (PID=62117) to work on /opt/airflow/dags/loader.py
[2023-12-21T00:30:57.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T00:30:57.972+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:30:57.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T00:30:57.975+0000] {logging_mixin.py:188} INFO - [2023-12-21T00:30:57.975+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T00:30:57.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T00:30:58.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.286 seconds
[2023-12-21T06:57:45.390+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/loader.py
[2023-12-21T06:57:45.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T06:57:45.797+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:57:45.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T06:57:46.154+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:57:45.801+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T06:57:46.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T06:57:46.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 1.025 seconds
[2023-12-21T06:58:17.223+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/loader.py
[2023-12-21T06:58:17.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T06:58:17.252+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:58:17.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T06:58:17.256+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:58:17.255+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T06:58:17.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T06:58:17.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.267 seconds
[2023-12-21T06:58:47.806+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/loader.py
[2023-12-21T06:58:47.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T06:58:47.811+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:58:47.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T06:58:47.816+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:58:47.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T06:58:47.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T06:58:48.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.462 seconds
[2023-12-21T06:59:18.774+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/loader.py
[2023-12-21T06:59:18.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T06:59:18.932+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:59:18.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T06:59:18.937+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:59:18.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T06:59:18.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T06:59:19.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.871 seconds
[2023-12-21T06:59:50.675+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/loader.py
[2023-12-21T06:59:50.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T06:59:50.736+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:59:50.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T06:59:50.741+0000] {logging_mixin.py:188} INFO - [2023-12-21T06:59:50.740+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T06:59:50.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T06:59:50.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.224 seconds
[2023-12-21T07:00:24.826+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:00:25.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:00:25.158+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:00:25.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:00:25.164+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:00:25.162+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:00:25.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:00:26.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 1.492 seconds
[2023-12-21T07:00:57.116+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:00:57.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:00:57.285+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:00:57.285+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:00:57.290+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:00:57.289+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:00:57.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:00:57.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.641 seconds
[2023-12-21T07:01:33.496+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:01:33.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:01:33.728+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:01:33.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:01:33.732+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:01:33.731+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:01:33.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:01:34.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.548 seconds
[2023-12-21T07:02:04.557+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:02:04.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:02:04.768+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:02:04.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:02:04.772+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:02:04.771+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:02:04.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:02:05.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.455 seconds
[2023-12-21T07:02:35.868+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:02:35.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:02:35.948+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:02:35.947+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:02:35.959+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:02:35.958+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:02:35.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:02:36.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.307 seconds
[2023-12-21T07:03:06.325+0000] {processor.py:161} INFO - Started process (PID=500) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:03:06.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:03:06.329+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:03:06.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:03:06.332+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:03:06.332+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:03:06.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:03:06.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.271 seconds
[2023-12-21T07:03:36.673+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:03:36.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:03:36.746+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:03:36.745+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:03:36.751+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:03:36.749+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:03:36.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:03:36.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.237 seconds
[2023-12-21T07:04:07.054+0000] {processor.py:161} INFO - Started process (PID=609) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:04:07.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:04:07.057+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:04:07.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:04:07.061+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:04:07.060+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:04:07.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:04:07.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.255 seconds
[2023-12-21T07:04:37.944+0000] {processor.py:161} INFO - Started process (PID=664) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:04:38.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:04:38.048+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:04:38.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:04:38.053+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:04:38.052+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:04:38.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:04:38.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.484 seconds
[2023-12-21T07:05:08.671+0000] {processor.py:161} INFO - Started process (PID=721) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:05:08.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:05:08.796+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:05:08.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:05:08.800+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:05:08.799+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:05:08.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:05:09.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.486 seconds
[2023-12-21T07:05:39.538+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:05:39.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:05:39.544+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:05:39.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:05:39.551+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:05:39.549+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:05:39.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:05:39.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.074 seconds
[2023-12-21T07:06:09.861+0000] {processor.py:161} INFO - Started process (PID=833) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:06:09.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:06:09.888+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:06:09.888+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:06:09.892+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:06:09.891+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:06:09.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:06:09.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.080 seconds
[2023-12-21T07:06:40.311+0000] {processor.py:161} INFO - Started process (PID=889) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:06:40.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:06:40.331+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:06:40.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:06:40.339+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:06:40.337+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:06:40.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:06:40.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.180 seconds
[2023-12-21T07:07:10.714+0000] {processor.py:161} INFO - Started process (PID=945) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:07:10.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:07:10.718+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:07:10.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:07:10.722+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:07:10.721+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:07:10.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:07:10.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.163 seconds
[2023-12-21T07:07:41.651+0000] {processor.py:161} INFO - Started process (PID=1001) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:07:41.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:07:41.679+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:07:41.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:07:41.683+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:07:41.682+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:07:41.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:07:41.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.090 seconds
[2023-12-21T07:08:11.904+0000] {processor.py:161} INFO - Started process (PID=1057) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:08:11.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:08:11.936+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:08:11.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:08:12.097+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:08:11.989+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:08:12.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:08:12.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.299 seconds
[2023-12-21T07:08:42.271+0000] {processor.py:161} INFO - Started process (PID=1113) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:08:42.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:08:42.278+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:08:42.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:08:42.286+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:08:42.284+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:08:42.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:08:42.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.113 seconds
[2023-12-21T07:09:12.584+0000] {processor.py:161} INFO - Started process (PID=1169) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:09:12.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:09:12.650+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:09:12.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:09:12.654+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:09:12.653+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:09:12.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:09:12.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.133 seconds
[2023-12-21T07:09:43.483+0000] {processor.py:161} INFO - Started process (PID=1224) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:09:43.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:09:43.530+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:09:43.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:09:43.535+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:09:43.534+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:09:43.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:09:43.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.141 seconds
[2023-12-21T07:10:13.985+0000] {processor.py:161} INFO - Started process (PID=1280) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:10:14.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:10:14.034+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:10:14.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:10:14.038+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:10:14.037+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:10:14.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:10:14.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.104 seconds
[2023-12-21T07:10:44.451+0000] {processor.py:161} INFO - Started process (PID=1337) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:10:44.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:10:44.455+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:10:44.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:10:44.459+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:10:44.457+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:10:44.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:10:44.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.055 seconds
[2023-12-21T07:11:14.709+0000] {processor.py:161} INFO - Started process (PID=1394) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:11:14.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:11:14.713+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:11:14.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:11:14.719+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:11:14.717+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:11:14.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:11:14.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.073 seconds
[2023-12-21T07:11:45.091+0000] {processor.py:161} INFO - Started process (PID=1450) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:11:45.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:11:45.165+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:11:45.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:11:45.168+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:11:45.168+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:11:45.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:11:45.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.136 seconds
[2023-12-21T07:12:15.774+0000] {processor.py:161} INFO - Started process (PID=1506) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:12:15.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:12:15.778+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:12:15.778+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:12:15.783+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:12:15.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:12:15.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:12:15.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.058 seconds
[2023-12-21T07:12:46.499+0000] {processor.py:161} INFO - Started process (PID=1562) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:12:46.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:12:46.528+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:12:46.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:12:46.532+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:12:46.531+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:12:46.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:12:46.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.114 seconds
[2023-12-21T07:13:16.860+0000] {processor.py:161} INFO - Started process (PID=1618) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:13:16.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:13:16.864+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:13:16.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:13:16.868+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:13:16.867+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:13:16.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:13:16.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.112 seconds
[2023-12-21T07:13:47.332+0000] {processor.py:161} INFO - Started process (PID=1673) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:13:47.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:13:47.343+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:13:47.343+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:13:47.348+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:13:47.347+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:13:47.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:13:47.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.063 seconds
[2023-12-21T07:14:17.497+0000] {processor.py:161} INFO - Started process (PID=1730) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:14:17.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:14:17.501+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:14:17.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:14:17.504+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:14:17.503+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:14:17.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:14:17.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.114 seconds
[2023-12-21T07:14:47.970+0000] {processor.py:161} INFO - Started process (PID=1785) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:14:47.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:14:47.995+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:14:47.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:14:47.999+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:14:47.998+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:14:47.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:14:48.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.079 seconds
[2023-12-21T07:15:18.372+0000] {processor.py:161} INFO - Started process (PID=1840) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:15:18.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:15:18.376+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:15:18.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:15:18.381+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:15:18.380+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:15:18.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:15:18.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.075 seconds
[2023-12-21T07:15:49.231+0000] {processor.py:161} INFO - Started process (PID=1894) to work on /opt/airflow/dags/loader.py
[2023-12-21T07:15:49.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loader.py for tasks to queue
[2023-12-21T07:15:49.327+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:15:49.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/loader.py
[2023-12-21T07:15:49.332+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:15:49.331+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/loader.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:15:49.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loader.py
[2023-12-21T07:15:49.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loader.py took 0.164 seconds
