[2023-12-21T07:18:18.855+0000] {processor.py:161} INFO - Started process (PID=2168) to work on /opt/airflow/dags/main.py
[2023-12-21T07:18:18.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:18:18.857+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:18:18.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:18:18.863+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:18:18.862+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:18:18.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:18:18.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.051 seconds
[2023-12-21T07:18:49.247+0000] {processor.py:161} INFO - Started process (PID=2224) to work on /opt/airflow/dags/main.py
[2023-12-21T07:18:49.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:18:49.250+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:18:49.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:18:49.254+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:18:49.253+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:18:49.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:18:49.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.180 seconds
[2023-12-21T07:19:19.579+0000] {processor.py:161} INFO - Started process (PID=2280) to work on /opt/airflow/dags/main.py
[2023-12-21T07:19:19.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:19:19.602+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:19:19.601+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:19:19.605+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:19:19.604+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:19:19.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:19:19.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.069 seconds
[2023-12-21T07:19:50.335+0000] {processor.py:161} INFO - Started process (PID=2336) to work on /opt/airflow/dags/main.py
[2023-12-21T07:19:50.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:19:50.337+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:19:50.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:19:50.341+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:19:50.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:19:50.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:19:50.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.169 seconds
[2023-12-21T07:20:21.052+0000] {processor.py:161} INFO - Started process (PID=2391) to work on /opt/airflow/dags/main.py
[2023-12-21T07:20:21.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:20:21.070+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:20:21.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:20:21.074+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:20:21.073+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:20:21.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:20:21.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.065 seconds
[2023-12-21T07:20:51.919+0000] {processor.py:161} INFO - Started process (PID=2447) to work on /opt/airflow/dags/main.py
[2023-12-21T07:20:51.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:20:51.921+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:20:51.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:20:51.926+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:20:51.925+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:20:51.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:20:51.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.064 seconds
[2023-12-21T07:21:22.134+0000] {processor.py:161} INFO - Started process (PID=2501) to work on /opt/airflow/dags/main.py
[2023-12-21T07:21:22.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:21:22.162+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:21:22.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:21:22.166+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:21:22.165+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:21:22.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:21:22.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.064 seconds
[2023-12-21T07:21:52.420+0000] {processor.py:161} INFO - Started process (PID=2554) to work on /opt/airflow/dags/main.py
[2023-12-21T07:21:52.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:21:52.423+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:21:52.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:21:52.428+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:21:52.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:21:52.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:21:52.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.174 seconds
[2023-12-21T07:22:23.450+0000] {processor.py:161} INFO - Started process (PID=2610) to work on /opt/airflow/dags/main.py
[2023-12-21T07:22:23.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:22:23.528+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:22:23.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:22:23.534+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:22:23.533+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:22:23.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:22:23.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.173 seconds
[2023-12-21T07:22:54.101+0000] {processor.py:161} INFO - Started process (PID=2666) to work on /opt/airflow/dags/main.py
[2023-12-21T07:22:54.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:22:54.104+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:22:54.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:22:54.110+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:22:54.108+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:22:54.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:22:54.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.088 seconds
[2023-12-21T07:23:24.643+0000] {processor.py:161} INFO - Started process (PID=2722) to work on /opt/airflow/dags/main.py
[2023-12-21T07:23:24.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:23:24.737+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:23:24.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:23:24.741+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:23:24.740+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:23:24.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:23:24.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.143 seconds
[2023-12-21T07:23:55.212+0000] {processor.py:161} INFO - Started process (PID=2778) to work on /opt/airflow/dags/main.py
[2023-12-21T07:23:55.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:23:55.214+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:23:55.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:23:55.220+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:23:55.219+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:23:55.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:23:55.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.063 seconds
[2023-12-21T07:24:25.478+0000] {processor.py:161} INFO - Started process (PID=2834) to work on /opt/airflow/dags/main.py
[2023-12-21T07:24:25.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:24:25.480+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:24:25.479+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:24:25.484+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:24:25.483+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:24:25.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:24:25.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.088 seconds
[2023-12-21T07:24:56.476+0000] {processor.py:161} INFO - Started process (PID=2890) to work on /opt/airflow/dags/main.py
[2023-12-21T07:24:56.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:24:56.479+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:24:56.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:24:56.484+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:24:56.483+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:24:56.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:24:56.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.048 seconds
[2023-12-21T07:25:27.277+0000] {processor.py:161} INFO - Started process (PID=2946) to work on /opt/airflow/dags/main.py
[2023-12-21T07:25:27.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:25:27.279+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:25:27.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:25:27.284+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:25:27.283+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:25:27.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:25:27.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.146 seconds
[2023-12-21T07:25:58.168+0000] {processor.py:161} INFO - Started process (PID=3002) to work on /opt/airflow/dags/main.py
[2023-12-21T07:25:58.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:25:58.191+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:25:58.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:25:58.195+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:25:58.194+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:25:58.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:25:58.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.073 seconds
[2023-12-21T07:26:28.594+0000] {processor.py:161} INFO - Started process (PID=3058) to work on /opt/airflow/dags/main.py
[2023-12-21T07:26:28.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:26:28.596+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:26:28.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:26:28.602+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:26:28.600+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:26:28.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:26:28.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.067 seconds
[2023-12-21T07:26:59.444+0000] {processor.py:161} INFO - Started process (PID=3114) to work on /opt/airflow/dags/main.py
[2023-12-21T07:26:59.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:26:59.472+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:26:59.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:26:59.477+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:26:59.476+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:26:59.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:26:59.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.103 seconds
[2023-12-21T07:27:30.101+0000] {processor.py:161} INFO - Started process (PID=3169) to work on /opt/airflow/dags/main.py
[2023-12-21T07:27:30.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:27:30.103+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:27:30.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:27:30.109+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:27:30.107+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:27:30.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:27:30.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.081 seconds
[2023-12-21T07:28:00.908+0000] {processor.py:161} INFO - Started process (PID=3224) to work on /opt/airflow/dags/main.py
[2023-12-21T07:28:00.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:28:01.004+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:28:01.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:28:01.009+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:28:01.008+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:28:01.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:28:01.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.326 seconds
[2023-12-21T07:28:31.738+0000] {processor.py:161} INFO - Started process (PID=3280) to work on /opt/airflow/dags/main.py
[2023-12-21T07:28:31.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:28:31.741+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:28:31.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:28:31.746+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:28:31.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:28:31.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:28:31.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.205 seconds
[2023-12-21T07:29:02.090+0000] {processor.py:161} INFO - Started process (PID=3336) to work on /opt/airflow/dags/main.py
[2023-12-21T07:29:02.091+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:29:02.093+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:29:02.092+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:29:02.097+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:29:02.096+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:29:02.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:29:02.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.143 seconds
[2023-12-21T07:29:32.426+0000] {processor.py:161} INFO - Started process (PID=3391) to work on /opt/airflow/dags/main.py
[2023-12-21T07:29:32.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:29:32.527+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:29:32.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:29:32.531+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:29:32.530+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:29:32.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:29:32.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.167 seconds
[2023-12-21T07:30:02.810+0000] {processor.py:161} INFO - Started process (PID=3446) to work on /opt/airflow/dags/main.py
[2023-12-21T07:30:02.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:30:02.813+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:30:02.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:30:02.818+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:30:02.817+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:30:02.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:30:02.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.182 seconds
[2023-12-21T07:30:33.892+0000] {processor.py:161} INFO - Started process (PID=3502) to work on /opt/airflow/dags/main.py
[2023-12-21T07:30:34.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:30:34.007+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:30:34.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:30:34.016+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:30:34.013+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:30:34.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:30:34.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.194 seconds
[2023-12-21T07:31:04.895+0000] {processor.py:161} INFO - Started process (PID=3558) to work on /opt/airflow/dags/main.py
[2023-12-21T07:31:04.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:31:04.897+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:31:04.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:31:04.901+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:31:04.899+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:31:04.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:31:05.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.165 seconds
[2023-12-21T07:31:35.439+0000] {processor.py:161} INFO - Started process (PID=3613) to work on /opt/airflow/dags/main.py
[2023-12-21T07:31:35.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:31:35.542+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:31:35.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:31:35.545+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:31:35.544+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:31:35.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:31:35.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.148 seconds
[2023-12-21T07:32:05.999+0000] {processor.py:161} INFO - Started process (PID=3669) to work on /opt/airflow/dags/main.py
[2023-12-21T07:32:06.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:32:06.001+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:32:06.001+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:32:06.005+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:32:06.004+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:32:06.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:32:06.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.052 seconds
[2023-12-21T07:32:36.236+0000] {processor.py:161} INFO - Started process (PID=3725) to work on /opt/airflow/dags/main.py
[2023-12-21T07:32:36.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:32:36.276+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:32:36.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:32:36.282+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:32:36.281+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:32:36.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:32:36.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.120 seconds
[2023-12-21T07:33:07.033+0000] {processor.py:161} INFO - Started process (PID=3781) to work on /opt/airflow/dags/main.py
[2023-12-21T07:33:07.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:33:07.048+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:33:07.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:33:07.058+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:33:07.052+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:33:07.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:33:07.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.153 seconds
[2023-12-21T07:33:37.545+0000] {processor.py:161} INFO - Started process (PID=3837) to work on /opt/airflow/dags/main.py
[2023-12-21T07:33:37.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:33:37.550+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:33:37.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:33:37.557+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:33:37.555+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:33:37.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:33:37.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.125 seconds
[2023-12-21T07:34:07.835+0000] {processor.py:161} INFO - Started process (PID=3893) to work on /opt/airflow/dags/main.py
[2023-12-21T07:34:07.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:34:07.838+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:34:07.837+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:34:07.844+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:34:07.842+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:34:07.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:34:07.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.068 seconds
[2023-12-21T07:34:38.818+0000] {processor.py:161} INFO - Started process (PID=3949) to work on /opt/airflow/dags/main.py
[2023-12-21T07:34:38.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:34:38.842+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:34:38.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:34:38.846+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:34:38.845+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:34:38.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:34:38.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.069 seconds
[2023-12-21T07:35:09.201+0000] {processor.py:161} INFO - Started process (PID=4005) to work on /opt/airflow/dags/main.py
[2023-12-21T07:35:09.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:35:09.203+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:35:09.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:35:09.207+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:35:09.206+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:35:09.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:35:09.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.068 seconds
[2023-12-21T07:35:39.593+0000] {processor.py:161} INFO - Started process (PID=4061) to work on /opt/airflow/dags/main.py
[2023-12-21T07:35:39.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:35:39.724+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:35:39.724+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:35:39.728+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:35:39.727+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:35:39.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:35:39.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.183 seconds
[2023-12-21T07:36:10.081+0000] {processor.py:161} INFO - Started process (PID=4116) to work on /opt/airflow/dags/main.py
[2023-12-21T07:36:10.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:36:10.083+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:36:10.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:36:10.087+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:36:10.086+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:36:10.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:36:10.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.117 seconds
[2023-12-21T07:36:40.333+0000] {processor.py:161} INFO - Started process (PID=4173) to work on /opt/airflow/dags/main.py
[2023-12-21T07:36:40.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:36:40.357+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:36:40.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:36:40.360+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:36:40.359+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:36:40.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:36:40.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.076 seconds
[2023-12-21T07:37:11.303+0000] {processor.py:161} INFO - Started process (PID=4229) to work on /opt/airflow/dags/main.py
[2023-12-21T07:37:11.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:37:11.305+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:37:11.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:37:11.309+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:37:11.308+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:37:11.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:37:11.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.160 seconds
[2023-12-21T07:37:41.722+0000] {processor.py:161} INFO - Started process (PID=4285) to work on /opt/airflow/dags/main.py
[2023-12-21T07:37:41.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:37:41.821+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:37:41.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:37:41.825+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:37:41.824+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:37:41.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:37:41.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.163 seconds
[2023-12-21T07:38:12.448+0000] {processor.py:161} INFO - Started process (PID=4341) to work on /opt/airflow/dags/main.py
[2023-12-21T07:38:12.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:38:12.450+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:38:12.450+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:38:12.455+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:38:12.454+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:38:12.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:38:12.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.222 seconds
[2023-12-21T07:38:42.860+0000] {processor.py:161} INFO - Started process (PID=4396) to work on /opt/airflow/dags/main.py
[2023-12-21T07:38:42.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:38:42.956+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:38:42.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:38:42.960+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:38:42.959+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:38:42.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:38:42.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.142 seconds
[2023-12-21T07:39:13.143+0000] {processor.py:161} INFO - Started process (PID=4452) to work on /opt/airflow/dags/main.py
[2023-12-21T07:39:13.144+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:39:13.145+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:39:13.145+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:39:13.149+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:39:13.148+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:39:13.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:39:13.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.050 seconds
[2023-12-21T07:39:43.265+0000] {processor.py:161} INFO - Started process (PID=4508) to work on /opt/airflow/dags/main.py
[2023-12-21T07:39:43.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:39:43.288+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:39:43.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:39:43.292+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:39:43.291+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:39:43.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:39:43.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.066 seconds
[2023-12-21T07:40:13.986+0000] {processor.py:161} INFO - Started process (PID=4561) to work on /opt/airflow/dags/main.py
[2023-12-21T07:40:13.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:40:13.988+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:40:13.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:40:13.992+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:40:13.991+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:40:13.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:40:14.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.047 seconds
[2023-12-21T07:40:44.457+0000] {processor.py:161} INFO - Started process (PID=4617) to work on /opt/airflow/dags/main.py
[2023-12-21T07:40:44.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:40:44.460+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:40:44.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:40:44.466+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:40:44.464+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:40:44.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:40:44.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.080 seconds
[2023-12-21T07:41:15.144+0000] {processor.py:161} INFO - Started process (PID=4672) to work on /opt/airflow/dags/main.py
[2023-12-21T07:41:15.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:41:15.146+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:41:15.146+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:41:15.150+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:41:15.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:41:15.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:41:15.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.163 seconds
[2023-12-21T07:41:45.916+0000] {processor.py:161} INFO - Started process (PID=4728) to work on /opt/airflow/dags/main.py
[2023-12-21T07:41:45.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:41:45.930+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:41:45.930+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:41:45.933+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:41:45.933+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:41:45.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:41:45.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.066 seconds
[2023-12-21T07:42:16.367+0000] {processor.py:161} INFO - Started process (PID=4785) to work on /opt/airflow/dags/main.py
[2023-12-21T07:42:16.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:42:16.370+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:42:16.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:42:16.376+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:42:16.374+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:42:16.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:42:16.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.069 seconds
[2023-12-21T07:42:47.101+0000] {processor.py:161} INFO - Started process (PID=4841) to work on /opt/airflow/dags/main.py
[2023-12-21T07:42:47.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:42:47.106+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:42:47.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:42:47.111+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:42:47.110+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:42:47.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:42:47.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.057 seconds
[2023-12-21T07:43:17.422+0000] {processor.py:161} INFO - Started process (PID=4897) to work on /opt/airflow/dags/main.py
[2023-12-21T07:43:17.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:43:17.424+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:43:17.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:43:17.428+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:43:17.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:43:17.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:43:17.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.101 seconds
[2023-12-21T07:43:47.918+0000] {processor.py:161} INFO - Started process (PID=4953) to work on /opt/airflow/dags/main.py
[2023-12-21T07:43:47.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:43:47.933+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:43:47.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:43:47.937+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:43:47.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:43:47.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:43:47.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-12-21T07:44:18.847+0000] {processor.py:161} INFO - Started process (PID=5009) to work on /opt/airflow/dags/main.py
[2023-12-21T07:44:18.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:44:18.858+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:44:18.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:44:18.864+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:44:18.862+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:44:18.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:44:19.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.211 seconds
[2023-12-21T07:44:49.341+0000] {processor.py:161} INFO - Started process (PID=5064) to work on /opt/airflow/dags/main.py
[2023-12-21T07:44:49.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:44:49.374+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:44:49.374+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:44:49.378+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:44:49.377+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:44:49.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:44:49.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.116 seconds
[2023-12-21T07:45:19.972+0000] {processor.py:161} INFO - Started process (PID=5120) to work on /opt/airflow/dags/main.py
[2023-12-21T07:45:19.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:45:19.976+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:45:19.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:45:19.982+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:45:19.981+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:45:19.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:45:20.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.069 seconds
[2023-12-21T07:45:50.149+0000] {processor.py:161} INFO - Started process (PID=5175) to work on /opt/airflow/dags/main.py
[2023-12-21T07:45:50.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:45:50.188+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:45:50.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:45:50.194+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:45:50.192+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:45:50.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:45:50.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.116 seconds
[2023-12-21T07:46:20.408+0000] {processor.py:161} INFO - Started process (PID=5231) to work on /opt/airflow/dags/main.py
[2023-12-21T07:46:20.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:46:20.410+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:46:20.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:46:20.416+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:46:20.414+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:46:20.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:46:20.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.091 seconds
[2023-12-21T07:46:50.949+0000] {processor.py:161} INFO - Started process (PID=5287) to work on /opt/airflow/dags/main.py
[2023-12-21T07:46:50.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:46:50.951+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:46:50.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:46:50.956+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:46:50.955+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:46:50.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:46:50.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.047 seconds
[2023-12-21T07:47:21.368+0000] {processor.py:161} INFO - Started process (PID=5343) to work on /opt/airflow/dags/main.py
[2023-12-21T07:47:21.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:47:21.370+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:47:21.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:47:21.374+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:47:21.373+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:47:21.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:47:21.425+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.062 seconds
[2023-12-21T07:47:51.707+0000] {processor.py:161} INFO - Started process (PID=5399) to work on /opt/airflow/dags/main.py
[2023-12-21T07:47:51.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:47:51.849+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:47:51.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:47:51.853+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:47:51.852+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:47:51.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:47:52.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.322 seconds
[2023-12-21T07:48:22.322+0000] {processor.py:161} INFO - Started process (PID=5455) to work on /opt/airflow/dags/main.py
[2023-12-21T07:48:22.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:48:22.324+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:48:22.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:48:22.327+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:48:22.327+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:48:22.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:48:22.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.086 seconds
[2023-12-21T07:48:52.790+0000] {processor.py:161} INFO - Started process (PID=5510) to work on /opt/airflow/dags/main.py
[2023-12-21T07:48:52.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:48:52.861+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:48:52.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:48:52.865+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:48:52.864+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:48:52.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:48:52.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.191 seconds
[2023-12-21T07:49:23.043+0000] {processor.py:161} INFO - Started process (PID=5565) to work on /opt/airflow/dags/main.py
[2023-12-21T07:49:23.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:49:23.045+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:49:23.045+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:49:23.049+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:49:23.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:49:23.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:49:23.127+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.087 seconds
[2023-12-21T07:49:53.411+0000] {processor.py:161} INFO - Started process (PID=5620) to work on /opt/airflow/dags/main.py
[2023-12-21T07:49:53.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:49:53.442+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:49:53.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:49:53.446+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:49:53.445+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:49:53.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:49:53.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.079 seconds
[2023-12-21T07:50:24.085+0000] {processor.py:161} INFO - Started process (PID=5675) to work on /opt/airflow/dags/main.py
[2023-12-21T07:50:24.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:50:24.087+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:50:24.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:50:24.093+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:50:24.092+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:50:24.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:50:24.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.138 seconds
[2023-12-21T07:50:55.002+0000] {processor.py:161} INFO - Started process (PID=5732) to work on /opt/airflow/dags/main.py
[2023-12-21T07:50:55.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:50:55.004+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:50:55.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:50:55.008+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:50:55.007+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:50:55.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:50:55.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.054 seconds
[2023-12-21T07:51:25.920+0000] {processor.py:161} INFO - Started process (PID=5788) to work on /opt/airflow/dags/main.py
[2023-12-21T07:51:25.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:51:25.923+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:51:25.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:51:25.927+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:51:25.926+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:51:25.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:51:25.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.071 seconds
[2023-12-21T07:51:56.255+0000] {processor.py:161} INFO - Started process (PID=5843) to work on /opt/airflow/dags/main.py
[2023-12-21T07:51:56.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:51:56.288+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:51:56.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:51:56.292+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:51:56.291+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:51:56.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:51:56.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.103 seconds
[2023-12-21T07:52:27.074+0000] {processor.py:161} INFO - Started process (PID=5899) to work on /opt/airflow/dags/main.py
[2023-12-21T07:52:27.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:52:27.076+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:52:27.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:52:27.081+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:52:27.080+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:52:27.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:52:27.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.149 seconds
[2023-12-21T07:52:57.968+0000] {processor.py:161} INFO - Started process (PID=5955) to work on /opt/airflow/dags/main.py
[2023-12-21T07:52:57.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:52:57.988+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:52:57.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:52:57.993+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:52:57.992+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 2, in <module>
    from my_airflow import DAG
ModuleNotFoundError: No module named 'my_airflow'
[2023-12-21T07:52:57.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:52:58.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-12-21T07:53:19.975+0000] {processor.py:161} INFO - Started process (PID=5994) to work on /opt/airflow/dags/main.py
[2023-12-21T07:53:19.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:53:19.977+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:53:19.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:53:20.488+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:53:20.486+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:53:20.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:53:20.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.558 seconds
[2023-12-21T07:53:50.693+0000] {processor.py:161} INFO - Started process (PID=6051) to work on /opt/airflow/dags/main.py
[2023-12-21T07:53:50.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:53:50.940+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:53:50.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:53:51.317+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:53:51.315+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:53:51.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:53:51.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.690 seconds
[2023-12-21T07:54:22.479+0000] {processor.py:161} INFO - Started process (PID=6108) to work on /opt/airflow/dags/main.py
[2023-12-21T07:54:22.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:54:22.481+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:54:22.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:54:23.208+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:54:23.201+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:54:23.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:54:23.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.006 seconds
[2023-12-21T07:54:54.100+0000] {processor.py:161} INFO - Started process (PID=6166) to work on /opt/airflow/dags/main.py
[2023-12-21T07:54:54.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:54:54.102+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:54:54.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:54:54.515+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:54:54.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:54:54.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:54:54.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.797 seconds
[2023-12-21T07:55:25.225+0000] {processor.py:161} INFO - Started process (PID=6223) to work on /opt/airflow/dags/main.py
[2023-12-21T07:55:25.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:55:25.516+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:55:25.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:55:26.101+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:55:26.098+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:55:26.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:55:27.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.935 seconds
[2023-12-21T07:55:57.297+0000] {processor.py:161} INFO - Started process (PID=6280) to work on /opt/airflow/dags/main.py
[2023-12-21T07:55:57.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:55:57.299+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:55:57.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:55:57.720+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:55:57.717+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:55:57.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:55:58.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 0.712 seconds
[2023-12-21T07:56:28.385+0000] {processor.py:161} INFO - Started process (PID=6337) to work on /opt/airflow/dags/main.py
[2023-12-21T07:56:28.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:56:28.571+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:56:28.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:56:29.006+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:56:29.003+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:56:29.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:56:29.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.274 seconds
[2023-12-21T07:56:59.757+0000] {processor.py:161} INFO - Started process (PID=6395) to work on /opt/airflow/dags/main.py
[2023-12-21T07:57:00.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-12-21T07:57:00.054+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:57:00.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-12-21T07:57:00.636+0000] {logging_mixin.py:188} INFO - [2023-12-21T07:57:00.633+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 11, in <module>
    from script.transform_data import transform_data
ImportError: cannot import name 'transform_data' from 'script.transform_data' (/opt/airflow/dags/script/transform_data.py)
[2023-12-21T07:57:00.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-12-21T07:57:00.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/main.py took 1.005 seconds
